-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 13:24:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestionarmateriales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestionarmateriales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestionarmateriales` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gestionarmateriales` ;

-- -----------------------------------------------------
-- Table `gestionarmateriales`.`materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionarmateriales`.`materiales` (
  `idMateriales` INT NOT NULL AUTO_INCREMENT,
  `descripcionMaterial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMateriales`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionarmateriales`.`blacklistedtoken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionarmateriales`.`blacklistedtoken` (
  `idblacklistedtoken` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(1000) NULL DEFAULT NULL,
  `creacion` TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (`idblacklistedtoken`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionarmateriales`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionarmateriales`.`perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `Perfil` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionarmateriales`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionarmateriales`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `apellidoUsuario` VARCHAR(45) NOT NULL,
  `IdentificacionUsuario` VARCHAR(45) NOT NULL,
  `idPerfil` INT NOT NULL,
  `firstLogin` TINYINT NOT NULL,
  `emailUsuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  `blackListedTokenId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_perfil_idx` (`idPerfil` ASC) VISIBLE,
  INDEX `fk_Usuario_backendListToken_idx` (`blackListedTokenId` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_backendListToken`
    FOREIGN KEY (`blackListedTokenId`)
    REFERENCES `gestionarmateriales`.`blacklistedtoken` (`idblacklistedtoken`),
  CONSTRAINT `fk_Usuario_perfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `gestionarmateriales`.`perfil` (`idPerfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestionarmateriales`.`asignarmateriales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionarmateriales`.`asignarmateriales` (
  `idasignarMateriales` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL DEFAULT NULL,
  `idMateriales` INT NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idasignarMateriales`),
  INDEX `fk_asignarMateriales_Usuario_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_asignarMateriales_Materiales_idx` (`idMateriales` ASC) VISIBLE,
  CONSTRAINT `fk_asignarMateriales_Materiales`
    FOREIGN KEY (`idMateriales`)
    REFERENCES `gestionarmateriales`.`materiales` (`idMateriales`),
  CONSTRAINT `fk_asignarMateriales_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `gestionarmateriales`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
